### ISSUE TITLE
Feature: autocomplete for common header fields

### ISSUE THREAD

**Issue by adrian7** [endeepak/stub_on_web#1]
Would be nice to have autocomplete for commonly used headers as: Content-Type, Expiry, Cache-Control etc.

Thanks.

**Comment by endeepak** [comment]
@adrian7  Thanks for the suggestion. I've added all the fields listed in https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Response_fields as autocomplete options. The changes have been deployed to live site.
